modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="theoutback"
version="${file.jarVersion}"
displayName="The Outback"
logoFile="witchettygrub.png"
credits="My first curseforge mod"
authors="Phoenix_WB"
description='''
A mod dedicated to surviving and navigating the stunning Australian landscape.
'''

[[dependencies.theoutback]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.theoutback]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"