modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]]
modId="theoutback"
version="${file.jarVersion}"
displayName="The Outback"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="theoutback.png"
credits="Join my server for more development!: https://discord.gg/ykpkRJR9Kk"
authors="Phoenix_WB"

description='''

'''

[[dependencies.theoutback]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.theoutback]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
